# Generated by Django 5.2.5 on 2025-08-06 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания')),
                ('address1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес 1')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес 2')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион')),
                ('role', models.CharField(choices=[('buyer', 'Покупатель'), ('seller', 'Продавец'), ('admin', 'Администратор')], default='buyer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
